tasks:
  - name: install-dependencies
    before: |
      printf 'export PATH="$HOME%s:$PATH"\n' "/.astra/cli" >> $HOME/.bashrc
      printf 'unset JAVA_TOOL_OPTIONS\n' >> $HOME/.bashrc
      curl -Ls "https://dtsx.io/get-astra-cli-java" | bash >> ./install.log
    init: |
      docker pull cassandra:4.0
      pip install -U cqlsh
      # REMOVE USER VALIDATION -Y ON JAVA 17 INSTALLATION
      sed -i '1,$s/sdkman_auto_answer=false/sdkman_auto_answer=true/' /home/gitpod/.sdkman/etc/config 
      sed -i '1,$s/sdkman_selfupdate_enable=true/sdkman_selfupdate_enable=false/' /home/gitpod/.sdkman/etc/config 
      # JAVA17 INSTALL
      sdk install java
    command: | 
      docker run -p 9042:9042 -d \
                 --name Cassandra \
                 -v ${PWD}/config/cassandra.yaml:/etc/cassandra/cassandra.yaml \
                 -v ${PWD}/config/cassandra-rackdc.properties:/etc/cassandra/cassandra-rackdc.properties cassandra:4.0
      unset JAVA_TOOL_OPTIONS                 
      source /home/gitpod/.astra/cli/astra-init.sh
ports:
  - port: 9042
    onOpen: ignore
github:
  prebuilds:
    main: true
vscode:
   extensions:
    - https://github.com/HadesArchitect/katapod/releases/download/nightly/katapod-nightly.vsix

